name = "sichuanguapilong"
account_id = "1d3c896c3b5b4bbc027c4b8369f0d734"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
cwd = ""
destination = "dist"

[build.environment]
NODE_VERSION = "20"
